version: '3.8'
services:
  rabbitmq:
    image: rabbitmq:3.9-management
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: energydb
      POSTGRES_USER: energyuser
      POSTGRES_PASSWORD: energypass
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U energyuser"]
      interval: 10s
      timeout: 5s
      retries: 5

  producer:
    build: ./EnergyProducerService
    ports:
      - "8181:8181"
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_started
    environment:
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/energydb
      SPRING_DATASOURCE_USERNAME: energyuser
      SPRING_DATASOURCE_PASSWORD: energypass

  user:
    build: ./EnergyUserService
    ports:
      - "8182:8182"
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_started
    environment:
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/energydb
      SPRING_DATASOURCE_USERNAME: energyuser
      SPRING_DATASOURCE_PASSWORD: energypass

  usage:
    build: ./EnergyUsageService
    ports:
      - "8186:8186"
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_started
    environment:
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/energydb
      SPRING_DATASOURCE_USERNAME: energyuser
      SPRING_DATASOURCE_PASSWORD: energypass

  percentage:
    build: ./EnergyPercentageService
    ports:
      - "8184:8184"
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_started
    environment:
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/energydb
      SPRING_DATASOURCE_USERNAME: energyuser
      SPRING_DATASOURCE_PASSWORD: energypass

  energy-api:
    build: ./EnergyAPI
    ports:
      - "8180:8180"
    depends_on:
      producer:
        condition: service_started
      user:
        condition: service_started
      usage:
        condition: service_started
      percentage:
        condition: service_started
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/energydb
      SPRING_DATASOURCE_USERNAME: energyuser
      SPRING_DATASOURCE_PASSWORD: energypass

  energy-gui:
    build: ./EnergyGUI
    ports:
      - "8185:8185"
    depends_on:
      energy-api:
        condition: service_started